name: Build Custom RustDesk Windows
run-name: Build custom rustdesk windows only

on:
  workflow_dispatch:

env:
  RUSTDESK_BRANCH: "master"

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RENDEZVOUS_SERVER: ${{ secrets.RD_RENDEZVOUS_SERVER }}
      RS_PUB_KEY: ${{ secrets.RD_RS_PUB_KEY }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone official rustdesk + submodules
        run: |
          git clone --recursive --depth 1 --branch $env:RUSTDESK_BRANCH https://github.com/rustdesk/rustdesk.git src
        shell: pwsh

      - name: Patch config.rs Windows
        run: |
          $fp = "src/libs/hbb_common/src/config.rs"
          $raw = Get-Content $fp -Raw

          $sTemplate = 'pub const RENDEZVOUS_SERVERS: &''static [&''static str] = &["__SV__"];'
          $kTemplate = 'pub const RS_PUB_KEY: &''static str = "__KEY__";'

          $lineServer = $sTemplate.Replace("__SV__", $env:RENDEZVOUS_SERVER)
          $lineKey = $kTemplate.Replace("__KEY__", $env:RS_PUB_KEY)

          $raw = $raw -replace 'pub const RENDEZVOUS_SERVERS: &''static \[&''static str\] = &\[.*?\];', $lineServer
          $raw = $raw -replace 'pub const RS_PUB_KEY: &''static str = ".*?";', $lineKey
          $raw = $raw -replace 'custom_rendezvous_server:\s*false','custom_rendezvous_server: true'

          $raw = $raw -replace "`r",""
          $raw | Out-File $fp -Encoding utf8NoBOM
        shell: pwsh

      - name: Verify patched content
        working-directory: ./src
        run: |
          Select-String libs/hbb_common/src/config.rs -Pattern "RENDEZVOUS_SERVERS|RS_PUB_KEY|custom_rendezvous_server"
        shell: pwsh

      - name: Install MSVC Build Tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Rust
        run: |
          Invoke-WebRequest https://win.rustup.rs -OutFile rustup-init.exe
          ./rustup-init.exe -y --default-toolchain stable-x86_64-pc-windows-msvc
        shell: pwsh

      # 刷新系统PATH，让cargo/rustc在后续步骤可见
      - name: Reload PATH
        run: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          cargo --version
          rustc --version
        shell: pwsh

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Show flutter env
        working-directory: ./src
        run: |
          flutter --version
          flutter doctor -v
        shell: pwsh

      - name: Build Windows Release
        working-directory: ./src
        run: |
          flutter pub get
          flutter build windows --release
        shell: pwsh

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk‑win‑custom
          path: src/build/windows/x64/runner/Release/
